version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: tfgandreu-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tfgandreu
      MYSQL_USER: tfgandreu
      MYSQL_PASSWORD: tfgandreu_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  adminer:
    image: adminer:4
    container_name: tfgandreu-adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  db_data:
